baseURL: https://davidspencer.xyz
languageCode: en-us
title: David Spencer
theme: PaperMod

outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowToc: true

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "//favicon.ico>"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  profileMode:
    enabled: true
    title: "David Spencer" # optional default will be site title
    subtitle: "Random Thoughts and Tutorials"
    imageUrl: "/me.png" # optional
    imageTitle: "David spencer" # optional
    imageWidth: 360 # custom size
    imageHeight: 360 # custom size

    buttons:
      - name: posts
        url: posts

  socialIcons:
    - name: "email"
      url: "mailto:david@davidspencer.xyz"
    - name: "github"
      url: "https://github.com/Elevate08"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/davidjspencer/"

  editPost:
      URL: "https://github.com/Elevate08/davidspencer.xyz/blob/master/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
